src/apps/accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [

    # Perfil privado de usuario.
    url(
        regex=r'^profile/$',
        view=views.UserProfileView.as_view(),
        name='profile'
    ),

    # Perfil público de usuario.
    url(
        regex=r'^(?P<slug>\w+)/profile/$',
        view=views.UserProfilePublicView.as_view(),
        name='profile_public'
    ),

    # Actualizar perfil.
    url(
        regex=r'^profile/update/$',
        view=views.UserProfileUpdateView.as_view(),
        name='profile_update'
    ),

    # Cambiar/añadir avatar de usuario.
    url(
        regex=r'^avatar/update/$',
        view=views.UserAvatarUpdateView.as_view(),
        name='avatar_update'
    ),

    # Detalles opciones de usuario.
    url(
        regex=r'^options/$',
        view=views.UserOptionsDetailView.as_view(),
        name='options'
    ),

    # Form actualiza opciones de usuario.
    url(
        regex=r'^options/update/$',
        view=views.UserOptionsUpdateView.as_view(),
        name='options_update'
    ),

    # Detalles localización del usuario.
    url(
        regex=r'^location/$',
        view=views.UserLocationDetailView.as_view(),
        name='location'
    ),

    # Actualizar localización del usuario.
    url(
        regex=r'^location/update/$',
        view=views.UserLocationUpdateView.as_view(),
        name='location_update'
    ),
]

src/apps/alerts/urls.py
from django.conf.urls import url

from . import views

app_name = 'alerts'

urlpatterns = [

    # Detalles de una alerta.
    url(
        regex=r'^$',
        view=views.AlertUserListView.as_view(),
        name='list'
    ),

    # Detalles de una alerta.
    url(
        regex=r'^details/(?P<pk>\d+)/$',
        view=views.AlertDetailsView.as_view(),
        name='details'
    ),

    # Añadir una nueva alerta.
    url(
        regex=r'^add/(?P<category>[a-z]+)/$',
        view=views.AlertCreateView.as_view(),
        name='create'
    ),

    # Actualizar una alerta.
    url(
        regex=r'^update/(?P<pk>\d+)/$',
        view=views.AlertUpdateView.as_view(),
        name='update'
    ),

    # Elimina una alerta.
    url(
        regex=r'^delete/(?P<pk>\d+)/$',
        view=views.AlertDeleteView.as_view(),
        name='delete'
    ),

    # Elimina todas las alertas de un usuario.
    url(
        regex=r'^delete-all/$',
        view=views.AlertsAllDeleteView.as_view(),
        name='delete_all'
    ),
]

src/apps/blog/urls.py
from django.conf.urls import url

from . import views
from .feeds import LastedEntriesFeed

app_name = 'blog'

urlpatterns = [

    # Pagina principal del Blog, muestra todos los artículos.
    url(
        regex=r'^$',
        view=views.ArticleListView.as_view(),
        name='index'
    ),

    # Muestra un articulo.
    url(
        regex=r'^article/(?P<slug>[\w-]+)/$',
        view=views.ArticleDetailView.as_view(),
        name='article_detail'
    ),

    # Muestra la lista de etiquetas.
    url(
        regex=r'^tags/$',
        view=views.TagListView.as_view(),
        name='tag_list'
    ),

    # Muestra artículos por etiqueta.
    url(
        regex=r'^tag/(?P<slug>[\w-]+)/$',
        view=views.ArticleListByTagNameListView.as_view(),
        name='articles_by_tag'
    ),

    # Pagina principal de archives.
    url(
        regex=r'^archive/$',
        view=views.ArticleArchiveIndexView.as_view(),
        name='archive'
    ),

    # Archivo de artículos por año.
    url(
        regex=r'^archive/(?P<year>[\d]{4})/$',
        view=views.ArticleYearArchiveView.as_view(),
        name='archive_year'
    ),

    # Archivo de artículos por año/mes.
    url(
        regex=r'^archive/(?P<year>\d{4})/(?P<month>\d{1,2})/$',
        view=views.ArticleMonthArchiveView.as_view(month_format='%m'),
        name='archive_month'
    ),

    # Formulario para recomendar articulo.
    url(
        regex=r'^recommend/(?P<slug>[-\w]+)/$',
        view=views.ArticleRecommendView.as_view(),
        name='article_recommend'
    ),

    # Registro para recibir notificaciones de nuevos artículos.
    url(
        regex=r'^alerts/register/$',
        view=views.ArticleSubscribeRegisterView.as_view(),
        name='article_suscriber_register'
    ),

    # DesRegistro para recibir notificaciones de nuevos artículos.
    url(
        regex=r'^alerts/unregister/(?P<token_unsigned>[\w]{30})/$',
        view=views.ArticleSubscribeUnregisterView.as_view(),
        name='article_suscriber_unregister'
    ),

    # Feeds del blog.
    url(
        regex=r'^feed/$',
        view=LastedEntriesFeed(),
        name='feed'
    ),
]

src/apps/contact/urls.py
from django.conf.urls import url

from . import views

app_name = 'contact'

urlpatterns = [

    # Form de contacto.
    url(
        regex=r'^$',
        view=views.ContactView.as_view(),
        name='contact'
    ),

    # Lista de mensajes de contacto.
    url(
        regex=r'^messages/$',
        view=views.ContactMessageListView.as_view(),
        name='message_list'
    ),

    # Detalles de un mensaje.
    url(
        regex=r'^message/(?P<pk>\d+)/$',
        view=views.ContactMessageDetailView.as_view(),
        name='message_detail'
    ),
]

src/apps/gallery/urls.py
from django.conf.urls import url

from . import views

app_name = 'gallery'

urlpatterns = [

    # Muestra las imágenes asociadas a un anuncio.
    url(
        regex=r'^list/anuncio(?P<id_anuncio>\d+)/$',
        view=views.ImageAnuncioListView.as_view(),
        name='anuncio_gallery_list'
    ),

    # Añadir imágenes perteneciente a anuncio.
    url(
        regex=r'^add/anuncio(?P<id_anuncio>\d+)/$',
        view=views.ImageAnuncioCreateView.as_view(),
        name='image_anuncio_add'
    ),

    # Actualizar/Cambiar una imagen.
    url(
        regex=r'^update/image(?P<pk>\d+)/$',
        view=views.ImageAnuncioUpdateView.as_view(),
        name='image_anuncio_update'
    ),

    # Eliminar una imagen.
    url(
        regex=r'^delete/image(?P<pk>\d+)/$',
        view=views.ImageAnuncioDeleteView.as_view(),
        name='image_anuncio_delete'
    ),
]

src/apps/promos/urls.py
from django.conf.urls import include, url

from . import views
from .api import urls as api_urls

app_name = 'promos'

urlpatterns = [

    # Genera y envía un código de promoción a un usuario.
    url(
        regex=r'^generate/code/$',
        view=views.GenerateCodePromoView.as_view(),
        name='generate_code_promo'
    ),

    # Validación del un código.
    url(
        regex=r'^validate/$',
        view=views.PromoValidateCodeView.as_view(),
        name='validate'
    ),

    # API
    url(r'^api/', include(api_urls)),
]

src/apps/stats/urls.py
from django.conf.urls import url

from . import views

app_name = 'stats'

urlpatterns = [

    # Pagina principal de stats.
    url(
        regex=r'^$',
        view=views.AdminIndexView.as_view(),
        name='index'
    ),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.static import serve

from anuncios.sitemaps import AnunciosSitemap
from blog.sitemaps import BlogSitemap
from search.views import IndexSearchView
from utils.api import UserIpInfoApiView

# Sitemaps
sitemaps = {
    'anuncios': AnunciosSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    ##################################################
    # / Home page.
    url(r'^$', IndexSearchView.as_view(), name='home_page'),
    ##################################################

    # /accounts/*
    url(r'^accounts/', include('accounts.urls')),

    # /alerts/*
    url(r'^alerts/', include('alerts.urls')),

    # /anuncios/*
    url(r'^anuncios/', include('anuncios.urls')),

    # /auth/*
    url(r'^auth/', include('authentication.urls')),

    # /blog/*
    url(r'^blog/', include('blog.urls')),

    # /contact/*
    url(r'^contact/', include('contact.urls')),

    # /favorites/*
    url(r'^favorites/', include('favorites.urls')),

    # /images/*
    url(r'^gallery/', include('gallery.urls')),

    # /pages/*
    url(r'^pages/', include('pages.urls')),

    # /payments/*
    url(r'^payments/', include('payments.urls')),

    # /pmessages/*
    url(r'^pmessages/', include('pmessages.urls')),

    # /promos/*
    url(r'^promos/', include('promos.urls')),

    # /rating/*
    url(r'^ratings/', include('ratings.urls')),

    # /recommend/*
    url(r'^recommend/', include('recommend.urls')),

    # /recommend/*
    url(r'^search/', include('search.urls')),

    # /stats/*
    url(r'^stats/', include('stats.urls')),

    # /api-auth/*
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # /admin/*
    url(r'^sadmin/', admin.site.urls),
]

# Sitemaps para anuncios y blog.
urlpatterns.append(
    url(
        regex=r'^sitemap\.xml$',
        view=sitemap,
        kwargs={'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
)

# API
urlpatterns.append(

    # Obtener información de localización con la ip del usuario.
    # src/static/src/js/gmaps/geolocation.js
    # IMPORTANTE: Si se cambia el name, cambiarlo en el .js
    url(
        regex=r'^api/user-ip-info/$',
        view=UserIpInfoApiView.as_view(),
        name='api_user_ip_info'
    ),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    import debug_toolbar

    urlpatterns += [
        # /media/:<mixed>path/
        url(
            regex=r'^media/(?P<path>.*)$',
            view=serve,
            kwargs={'document_root': settings.MEDIA_ROOT}
        ),

        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

# Si se pone en DEBUG = False en desarrollo, para poder ver los static files.
# Muy importante, comentar cuando se termine.
# urlpatterns += [
#     url(
#         r'^media/(?P<path>.*)$',
#         serve,
#         {'document_root': settings.MEDIA_ROOT}
#     ),
#
#     url(
#         r'^static/(?P<path>.*)$',
#         serve,
#         {'document_root': settings.STATIC_ROOT}
#     ),
# ]

src/apps/accounts/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify

from dateutil import relativedelta

from localization.models import AbstractLocationModel
from utils.images import ImageResize
from utils.mixins.models import ImageUpdateModel

from . import settings as accounts_settings


class User(ImageUpdateModel, AbstractUser):
    """Perfil de usuario."""
    slug = models.SlugField(
        max_length=150,
        blank=True
    )
    avatar = models.ImageField(
        verbose_name='Avatar',
        upload_to=accounts_settings.ACCOUNTS_AVATAR_PATH,
        default='',
        blank=True
    )
    public_name = models.CharField(
        verbose_name='Nombre a mostrar',
        max_length=50,
        default='',
        blank=True
    )
    phone = models.CharField(
        verbose_name='Teléfono',
        max_length=30,
        blank=True,
        default=''
    )
    description = models.TextField(
        verbose_name='Descripción',
        blank=True,
        default=''
    )
    is_premium = models.BooleanField(
        verbose_name='¿Es cuenta Premium?',
        default=False
    )
    anuncios_premium = models.IntegerField(
        verbose_name='Numero de anuncios Premium',
        default=0
    )
    expire_premium_at = models.DateTimeField(
        verbose_name='Fecha de expiración cuenta Premium',
        blank=True
    )

    _image_fields = ['avatar']

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.old_avatar = None

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        """Comprueba si ha añadido o cambiado el avatar.

        Si acaba de crear la cuenta, se pondrá en self.expire_premium_at
        a un día anterior a now().
        """
        self.slug = slugify(self.username)
        if not self.pk:
            self.expire_premium_at = timezone.now() - timezone.timedelta(days=1)
        if self.avatar and self.old_avatar != self.avatar:
            super().save(*args, **kwargs)
            image_resize = ImageResize(self.avatar.path)
            image_resize.resize(
                save_path=self.avatar.path,
                width=accounts_settings.ACCOUNTS_AVATAR_WIDTH,
                height=accounts_settings.ACCOUNTS_AVATAR_HEIGHT
            )
            self.old_avatar = self.avatar
        else:
            super().save(*args, **kwargs)

    def get_absolute_url(self):
        """Obtener el URLConf para el perfil privado."""
        return reverse('accounts:profile')

    @property
    def get_avatar(self):
        """Obtener avatar usuario.

        Al usar get_avatar no requiere de {{ MEDIA_URL }}.

        Returns:
            str: Avatar del usuario o imagen por defecto.

            Si el usuario tiene un avatar, obtendrá el del usuario, en caso
            contrario, el avatar por defecto.
        """
        if not self.avatar or not self.avatar.path:
            return '{}{}/{}'.format(
                settings.MEDIA_URL,
                accounts_settings.ACCOUNTS_AVATAR_PATH,
                accounts_settings.ACCOUNTS_AVATAR_DEFAULT
            )
        return '{}/{}'.format(settings.MEDIA_URL, self.avatar)

    @property
    def get_public_name(self):
        """Obtiene el nombre público.

        Depende de si lo tiene puesto o no, si lo tiene puesto lo devolverá, en
        caso contrario, devolverá el username.
        """
        return self.public_name if self.public_name else self.username

    def update_premium(self, months):
        """Actualiza la cuenta Premium.

        Si Premium no esta activo o esta expirado, pondrá expire_premium_at a
        now(), en caso contrario, si esta activa y con tiempo, se le incrementara
        el tiempo de expiración mas los months.

        Args:
            months (int): Meses a incrementar.
        """
        if not self.is_premium:
            self.is_premium = True
        if self.expire_premium_at < timezone.now():
            self.expire_premium_at = timezone.now()
        self.expire_premium_at += relativedelta.relativedelta(months=months)

    def increase_anuncio(self):
        """Incrementa en 1 el numero de anuncios_premium."""
        self.anuncios_premium += 1

    def decrease_anuncio(self):
        """Decrementar en 1 el numero de anuncios_premium."""
        if self.anuncios_premium > 0:
            self.anuncios_premium -= 1


class UserOptions(models.Model):
    """Opciones de usuario."""
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        primary_key=True,
        verbose_name='Opciones de usuario',
        related_name='user_options'
    )
    phone_public = models.BooleanField(
        verbose_name='Teléfono público',
        default=False
    )
    address_public = models.BooleanField(
        verbose_name='Dirección publica',
        default=False
    )
    email_public = models.BooleanField(
        verbose_name='Email público',
        default=False
    )
    notify_precio_anuncio_baja = models.BooleanField(
        verbose_name='Notificar si el precio baja',
        default=True
    )

    class Meta:
        verbose_name = 'Opciones de usuario'
        verbose_name_plural = 'Opciones de usuarios'

    def __str__(self):
        return self.user.username


class UserLocation(AbstractLocationModel):
    """Localización del usuario."""
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        primary_key=True,
        verbose_name='Localización usuario',
        related_name='user_location'
    )

    class Meta:
        verbose_name = 'Localización de usuario'
        verbose_name_plural = 'Localizaciones de usuarios'

    def __str__(self):
        return self.user.username

src/apps/accounts/templates/accounts/_sidenavs.html
{% load utils_tags %}

{% if user.is_superuser %}
  <div class="list-group mb-4 mt-4 mt-lg-0">
    <div class="list-group-item active">Administración</div>

    <a class="list-group-item list-group-item-action pl-2 pl-2" href="{% url 'stats:index' %}">
      <i class="material-icons">timeline</i> Stats
    </a>
    <a class="list-group-item list-group-item-action pl-2" href="{% url 'promos:generate_code_promo' %}">
      <i class="material-icons">alarm_add</i> Promos
    </a>
    <a class="list-group-item list-group-item-action pl-2" href="{% url 'anuncios:list' %}">
      <i class="material-icons">featured_play_list</i> Lista de anuncios
    </a>
    <a class="list-group-item list-group-item-action pl-2" href="{% url 'blog:index' %}">
      <i class="material-icons">chrome_reader_mode</i> Blog
    </a>
    <a class="d-flex list-group-item list-group-item-action pl-2" href="{% url 'contact:message_list' %}">
      <span class="mr-auto">
        <i class="material-icons">contact_mail</i> Mensajes contacto
      </span>
      <span>
        <span class="badge badge-{% if CONTACT_MESSAGES_UNREAD %}success{% else %}secondary{% endif %}">
          {{ CONTACT_MESSAGES_UNREAD }}
        </span>
      </span>
    </a>
    <a class="list-group-item list-group-item-action pl-2" href="/admin/">
      <i class="material-icons">verified_user</i> Admin
    </a>
  </div>
{% endif %}

<div class="list-group mb-3">
  <div class="list-group-item active">Menú</div>

  <a class="list-group-item list-group-item-action pl-2" href="{% url 'accounts:profile' %}">
    <i class="material-icons">person</i> Perfil
  </a>
  <a class="list-group-item list-group-item-action pl-2" href="{% url 'accounts:location' %}">
    <i class="material-icons">language</i> Localización
  </a>
  <a class="list-group-item list-group-item-action pl-2" href="{% url 'accounts:options' %}">
    <i class="material-icons">settings</i> Opciones
  </a>
  <a class="list-group-item list-group-item-action pl-2" href="{% url 'alerts:list' %}">
    <i class="material-icons">notifications</i> Alertas
  </a>
  <a class="list-group-item list-group-item-action pl-2" href="{% url 'anuncios:list_by_owner' user.slug %}">
    <i class="material-icons">chrome_reader_mode</i> Mis anuncios
  </a>
  <a class="list-group-item list-group-item-action pl-2" href="{% url 'favorites:list' %}">
    <i class="material-icons">star</i> Favoritos
  </a>
  <a class="d-flex list-group-item list-group-item-action pl-2" href="{% url 'pmessages:inbox' %}">
    <span class="mr-auto">
      <i class="material-icons">message</i> Mensajes
    </span>
    <span>
      <span class="badge badge-{% if INBOX_COUNT %}success{% else %}secondary{% endif %}">
        {{ INBOX_COUNT|default:'0' }}
      </span>
    </span>
  </a>
</div>

src/apps/accounts/templates/accounts/avatar_update.html
{% extends "accounts/base_accounts.html" %}

{% block meta_description %}Actualizar avatar{% endblock meta_description %}
{% block head_title %}- Actualizar avatar{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>Actualizar avatar</h1>
    </section>
  </section>
{% endblock page_title %}

{% block accounts_content %}
  <section class="row">
    <div class="col-12">
      <div class="text-center">
        <img id="img-avatar"
             class="img-fluid z-depth-1"
             src="{{ user.get_avatar }}"
             alt="Avatar {{ user.username }}"
             width="120"
        >
        <hr>
      </div>

      <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label class="form-control-label" for="id_avatar">
              {% if user.avatar %}Cambiar avatar{% else %}Añadir avatar{% endif %}
            </label>
            <hr class="mt-1">
            <input id="id_avatar" class="form-control-file" type="file" name="avatar">
          </div>

          {% if form.avatar %}
            <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" name="delete_avatar" type="checkbox">
                Eliminar avatar
              </label>
            </div>
          {% endif %}

          <div class="mt-4">
            <button class="btn btn-primary" type="submit">Actualizar</button>
            <a class="btn btn-success" href="{% url 'accounts:profile' %}">Volver</a>
          </div>
      </form>
    </div>
  </section>
{% endblock accounts_content %}

{% block scripts %}
  <script>
    $(document).ready(function() {
      $('#id_avatar').change(function() {
        readImagePreview('#img-avatar', this);
      });
    });
  </script>
{% endblock scripts %}

src/apps/accounts/templates/accounts/base_accounts.html
{% extends "base.html" %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-3 order-2 order-lg-1">{% include "accounts/_sidenavs.html" %}</div>
      <div class="col-lg-9 order-1 order-lg-2">{% block accounts_content %}{% endblock accounts_content %}</div>
    </section>
  </section>
{% endblock content %}

src/apps/accounts/templates/accounts/location_update.html
{% extends "accounts/base_accounts.html" %}
{% load djtemplateforms_tags %}

{% block meta_description %}Editar localización{% endblock meta_description %}
{% block head_title %}- Editar localización{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>Editar localización</h1>
    </section>
  </section>
{% endblock page_title %}

{% block accounts_content %}
  <section class="row">
    <div class="col-12">
      <div class="alert alert-info alert-icon">
        La localización es útil para las búsquedas, mostrara el mapa en una zona aproximada a la que pongas.<br>
        Para los anunciantes, añadirá en el formulario parte de la localización en el anuncio.<br>
        Si además en las opciones de usuario lo pones como público, sera mostrados en el perfil
        público (<strong>No recomendado a particulares</strong>).
      </div>

      <form id="form-location" method="post" action="">
        {% csrf_token %}
        <div class="form-row">
          {% form form %}

          <div class="col-12">
            <a id="form-location-to-coords" class="btn btn-success" href="javascript:void(0);">Actualizar</a>
            <a class="btn btn-primary" href="{% url 'accounts:location' %}">Volver</a>
          </div>
        </div>
      </form>
    </div>
  </section>
{% endblock accounts_content %}

{% block scripts %}
  {% include "_gmaps_script.html" %}
{% endblock scripts %}

src/apps/accounts/templates/accounts/options_update.html
{% extends "accounts/base_accounts.html" %}
{% load djtemplateforms_tags %}

{% block meta_description %}Editar opciones{% endblock meta_description %}
{% block head_title %}- Editar opciones{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>Editar opciones</h1>
    </section>
  </section>
{% endblock page_title %}

{% block accounts_content %}
  <section class="row">
    <div class="col-12">
      <form method="post" action="">
        {% csrf_token %}
        <div class="form-row">
          {% form form %}

          <div class="col-12">
            <button class="btn btn-success" type="submit">Actualizar</button>
            <a class="btn btn-primary" href="{% url 'accounts:options' %}">Volver</a>
          </div>
        </div>

      </form>
    </div>
  </section>
{% endblock accounts_content %}

src/apps/accounts/templates/accounts/profile.html
{% extends "accounts/base_accounts.html" %}
{% load utils_tags %}

{% block meta_description %}Perfil de usuario{% endblock meta_description %}
{% block head_title %}- Perfil de usuario{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>Perfil de usuario</h1>
    </section>
  </section>
{% endblock page_title %}

{% block accounts_content %}
  <section class="row">
    <div class="col-12 text-center">
      <img class="img-fluid z-depth-1" src="{{ user.get_avatar }}" alt="Avatar" width="120px">

      <div class="my-3">
        <a data-toggle="tooltip" title="Editar avatar" href="{% url 'accounts:avatar_update' %}">
          <i class="material-icons">mode_edit</i>
        </a>
      </div>

      {% if user.description %}
        <div class="text-left">
          <h3 class="text-header">Descripción</h3>
          {% markdown user.description safe=False %}
        </div>
      {% endif %}
    </div>
  </section>

  <section class="row">
    <div class="col-12">
      <table class="table">
        <tbody>
          <tr>
            <td><i class="material-icons">person</i> Nombre de usuario</td>
            <td class="text-value">{{ user.username }}</td>
          </tr>
          <tr>
            <td><i class="material-icons">email</i> Email</td>
            <td class="text-value">
              {{ user.email }}
              <a data-toggle="tooltip"
                 data-placement="left"
                 title="Editar email"
                 href="{% url 'authentication:email_update' %}"
              >
                <i class="material-icons md-4 ml-2">mode_edit</i>
              </a>
            </td>
          </tr>
          <tr>
            <td><i class="material-icons">group</i> Nombre público</td>
            <td class="text-value">{{ user.get_public_name }}</td>
          </tr>
          <tr>
            <td><i class="material-icons">phone</i> Teléfono</td>
            <td class="text-value">{{ user.phone|default:'Sin datos' }}</td>
          </tr>
          <tr>
            <td><i class="material-icons">enhanced_encryption</i> Contraseña</td>
            <td class="text-value">
              ************
              <a data-toggle="tooltip"
                 data-placement="left"
                 title="Editar contraseña"
                 href="{% url 'authentication:password_change' %}"
              >
                <i class="material-icons md-4 ml-2">mode_edit</i>
              </a>
            </td>
          </tr>
          <tr>
            <td><i class="material-icons">payment</i> Tipo de cuenta</td>
            <td class="text-value">
              {% if user.is_premium %}
                <small class="text-muted"
                      data-toggle="tooltip"
                      data-placement="left"
                      title="Fecha de expiración"
                >
                  {{ user.expire_premium_at|date:'SHORT_DATE_FORMAT' }}
                </small>
                <span class="badge badge-success">Premium</span>
                <a data-toggle="tooltip"
                   data-placement="left"
                   title="Incrementar tiempo"
                   href="{% url 'payments:process_account_premium' %}">
                  <i class="material-icons">update</i>
                </a>
              {% else %}
                <span class="badge badge-secondary">Normal</span>
                <a data-toggle="tooltip"
                   data-placement="left"
                   title="Cambiar a cuenta premium"
                   href="{% url 'payments:process_account_premium' %}"
                >
                  <i class="material-icons">add</i>
                </a>
              {% endif %}
            </td>
          </tr>
          <tr>
            <td><i class="material-icons">payment</i> Anuncios premium</td>
            <td class="text-value">
              <span class="badge badge-{% if user.anuncios_premium %}success{% else %}secondary{% endif %}">
                {{ user.anuncios_premium }}
              </span>
              <a data-toggle="tooltip"
                  data-placement="left"
                  title="Añadir anuncio premium"
                  href="{% url 'payments:process_anuncio_premium' %}"
              >
                <i class="material-icons">add</i>
              </a>
            </td>
          </tr>
        </tbody>
      </table>

      <div class="text-center">
        <a class="btn btn-outline-success" href="{% url 'promos:validate' %}">
          <i class="material-icons">code</i> Añadir código de promoción
        </a>
      </div>

      <div class="text-center mt-3">
        <a class="btn btn-primary btn-sm" href="{% url 'accounts:profile_public' user.slug %}">
          <i class="material-icons">remove_red_eye</i> Ver perfil publico
        </a>
        <a class="btn btn-primary btn-sm" href="{% url 'accounts:profile_update' %}">
          <i class="material-icons">mode_edit</i> Editar perfil
        </a>
      </div>
    </div>
  </section>
{% endblock accounts_content %}