src/apps/accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [

    # Perfil privado de usuario.
    url(
        regex=r'^profile/$',
        view=views.UserProfileView.as_view(),
        name='profile'
    ),

    # Perfil público de usuario.
    url(
        regex=r'^(?P<slug>\w+)/profile/$',
        view=views.UserProfilePublicView.as_view(),
        name='profile_public'
    ),

    # Actualizar perfil.
    url(
        regex=r'^profile/update/$',
        view=views.UserProfileUpdateView.as_view(),
        name='profile_update'
    ),

    # Cambiar/añadir avatar de usuario.
    url(
        regex=r'^avatar/update/$',
        view=views.UserAvatarUpdateView.as_view(),
        name='avatar_update'
    ),

    # Detalles opciones de usuario.
    url(
        regex=r'^options/$',
        view=views.UserOptionsDetailView.as_view(),
        name='options'
    ),

    # Form actualiza opciones de usuario.
    url(
        regex=r'^options/update/$',
        view=views.UserOptionsUpdateView.as_view(),
        name='options_update'
    ),

    # Detalles localización del usuario.
    url(
        regex=r'^location/$',
        view=views.UserLocationDetailView.as_view(),
        name='location'
    ),

    # Actualizar localización del usuario.
    url(
        regex=r'^location/update/$',
        view=views.UserLocationUpdateView.as_view(),
        name='location_update'
    ),
]

src/apps/anuncios/urls.py
from django.conf.urls import include, url

from . import views
from .api import urls as api_urls

app_name = 'anuncios'

urlpatterns = [

    # Lista publica de anuncios (Actualmente desactivada para los usuarios).
    url(
        regex=r'^$',
        view=views.AnuncioListView.as_view(),
        name='list'
    ),

    # Lista de anuncios por id usuario.
    url(
        regex=r'^(?P<slug>\w+)/list/$',
        view=views.AnuncioListByOwnerView.as_view(),
        name='list_by_owner'
    ),

    # Detalles de un anuncio.
    url(
        regex=r'^details/(?P<pk>\d+)/$',
        view=views.AnuncioDetailView.as_view(),
        name='details'
    ),

    # Pagina principal de creación de anuncios.
    url(
        regex=r'^create/$',
        view=views.AnuncioCreateSelectListView.as_view(),
        name='create_select'
    ),

    # Create anuncio.
    url(
        regex=r'^create/(?P<category>\w+)/$',
        view=views.AnuncioCreateView.as_view(),
        name='create'
    ),

    # Update anuncio.
    url(
        regex=r'^update/(?P<category>\w+)/(?P<pk>\d+)/$',
        view=views.AnuncioUpdateView.as_view(),
        name='update'
    ),

    # Marcar como active=False un anuncio.
    url(
        regex=r'^deactivate/(?P<id_anuncio>\d+)/$',
        view=views.AnuncioDeactivateView.as_view(),
        name='deactivate'
    ),

    # Marcar como active=False un anuncio.
    url(
        regex=r'^activate/(?P<id_anuncio>\d+)/$',
        view=views.AnuncioActivateView.as_view(),
        name='activate'
    ),

    # Marcar como active=False un anuncio.
    url(
        regex=r'^convert/premium/(?P<id_anuncio>\d+)/$',
        view=views.AnuncioConvertPremiumView.as_view(),
        name='convert_anuncio_premium'
    ),

    # API
    url(r'^api/', include(api_urls)),
]

src/apps/gallery/urls.py
from django.conf.urls import url

from . import views

app_name = 'gallery'

urlpatterns = [

    # Muestra las imágenes asociadas a un anuncio.
    url(
        regex=r'^list/anuncio(?P<id_anuncio>\d+)/$',
        view=views.ImageAnuncioListView.as_view(),
        name='anuncio_gallery_list'
    ),

    # Añadir imágenes perteneciente a anuncio.
    url(
        regex=r'^add/anuncio(?P<id_anuncio>\d+)/$',
        view=views.ImageAnuncioCreateView.as_view(),
        name='image_anuncio_add'
    ),

    # Actualizar/Cambiar una imagen.
    url(
        regex=r'^update/image(?P<pk>\d+)/$',
        view=views.ImageAnuncioUpdateView.as_view(),
        name='image_anuncio_update'
    ),

    # Eliminar una imagen.
    url(
        regex=r'^delete/image(?P<pk>\d+)/$',
        view=views.ImageAnuncioDeleteView.as_view(),
        name='image_anuncio_delete'
    ),
]

src/apps/promos/urls.py
from django.conf.urls import include, url

from . import views
from .api import urls as api_urls

app_name = 'promos'

urlpatterns = [

    # Genera y envía un código de promoción a un usuario.
    url(
        regex=r'^generate/code/$',
        view=views.GenerateCodePromoView.as_view(),
        name='generate_code_promo'
    ),

    # Validación del un código.
    url(
        regex=r'^validate/$',
        view=views.PromoValidateCodeView.as_view(),
        name='validate'
    ),

    # API
    url(r'^api/', include(api_urls)),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.static import serve

from anuncios.sitemaps import AnunciosSitemap
from blog.sitemaps import BlogSitemap
from search.views import IndexSearchView
from utils.api import UserIpInfoApiView

# Sitemaps
sitemaps = {
    'anuncios': AnunciosSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    ##################################################
    # / Home page.
    url(r'^$', IndexSearchView.as_view(), name='home_page'),
    ##################################################

    # /accounts/*
    url(r'^accounts/', include('accounts.urls')),

    # /alerts/*
    url(r'^alerts/', include('alerts.urls')),

    # /anuncios/*
    url(r'^anuncios/', include('anuncios.urls')),

    # /auth/*
    url(r'^auth/', include('authentication.urls')),

    # /blog/*
    url(r'^blog/', include('blog.urls')),

    # /contact/*
    url(r'^contact/', include('contact.urls')),

    # /favorites/*
    url(r'^favorites/', include('favorites.urls')),

    # /images/*
    url(r'^gallery/', include('gallery.urls')),

    # /pages/*
    url(r'^pages/', include('pages.urls')),

    # /payments/*
    url(r'^payments/', include('payments.urls')),

    # /pmessages/*
    url(r'^pmessages/', include('pmessages.urls')),

    # /promos/*
    url(r'^promos/', include('promos.urls')),

    # /rating/*
    url(r'^ratings/', include('ratings.urls')),

    # /recommend/*
    url(r'^recommend/', include('recommend.urls')),

    # /recommend/*
    url(r'^search/', include('search.urls')),

    # /stats/*
    url(r'^stats/', include('stats.urls')),

    # /api-auth/*
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # /admin/*
    url(r'^sadmin/', admin.site.urls),
]

# Sitemaps para anuncios y blog.
urlpatterns.append(
    url(
        regex=r'^sitemap\.xml$',
        view=sitemap,
        kwargs={'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
)

# API
urlpatterns.append(

    # Obtener información de localización con la ip del usuario.
    # src/static/src/js/gmaps/geolocation.js
    # IMPORTANTE: Si se cambia el name, cambiarlo en el .js
    url(
        regex=r'^api/user-ip-info/$',
        view=UserIpInfoApiView.as_view(),
        name='api_user_ip_info'
    ),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    import debug_toolbar

    urlpatterns += [
        # /media/:<mixed>path/
        url(
            regex=r'^media/(?P<path>.*)$',
            view=serve,
            kwargs={'document_root': settings.MEDIA_ROOT}
        ),

        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

# Si se pone en DEBUG = False en desarrollo, para poder ver los static files.
# Muy importante, comentar cuando se termine.
# urlpatterns += [
#     url(
#         r'^media/(?P<path>.*)$',
#         serve,
#         {'document_root': settings.MEDIA_ROOT}
#     ),
#
#     url(
#         r'^static/(?P<path>.*)$',
#         serve,
#         {'document_root': settings.STATIC_ROOT}
#     ),
# ]

src/apps/gallery/models.py
import os

from django.conf import settings
from django.db import models

from anuncios.models import Anuncio
from utils.images import ImageResize

from . import settings as images_settings


class ImageAnuncio(models.Model):
    """Imagen de un anuncio."""
    anuncio = models.ForeignKey(
        Anuncio,
        on_delete=models.CASCADE,
        verbose_name='Anuncio',
        related_name='image_anuncio',
    )
    image = models.ImageField(
        verbose_name='Imagen',
        upload_to=images_settings.GALLERY_IMAGE_PATH
    )
    thumbnail = models.CharField(
        verbose_name='Thumbnail',
        max_length=100,
        blank=True
    )
    description = models.CharField(
        verbose_name='Descripción',
        max_length=100,
        default='',
        blank=True
    )

    def __str__(self):
        """ID de la imagen para mostrarla en admin Anuncio."""
        return str(self.id)

    def save(self, *args, **kwargs):
        """Genera el nombre de thumbnail y elimina si se cambia.

        Si la imagen se ha cambiado, la antigua sera eliminada del disco, también
        genera el nombre para el thumbnail.

        Una imagen .png la convertirá a .jpeg para poderle aplicar los filtros,
        de lo contrario las imágenes .png pueden llegar a pasar mucho.

        Renombrar la extensión de .png a .jpg antes de manipular la imagen.

        Se ha de indicar en ImageResize.png2jpeg = True.
        """
        if not self.id:
            if self.image.name[-4:].lower() == '.png':
                self.image.name = '{}{}'.format(self.image.name[:-4], '.jpg')
        else:
            old_image = ImageAnuncio.objects.get(pk=self.id)
            old_image_path = old_image.image.path
            old_thumbnail_name = old_image.thumbnail
            if old_image_path != self.image.path:
                self._remove_old_images(old_image_path, old_thumbnail_name)
        # Es necesario guardar antes de asignar el nombre al thumbnail para
        # que luego el nombre sea el mismo.
        super().save(*args, **kwargs)
        self.thumbnail = images_settings.GALLERY_THUMBNAIL_PATH.format(
            os.path.basename(self.image.name)
        )
        super().save(*args, **kwargs)
        self._resize_images(png2jpeg=True)

    def _remove_old_images(self, old_image_path, old_thumbnail_name):
        """Elimina imagen y thumbnail del disco.

        Args:
            old_image_path (str): Path absoluto de la imagen.
            old_thumbnail_name (str): Nombre de la imagen (upload_to).
        """
        thumbnail_path = os.path.join(settings.MEDIA_ROOT, old_thumbnail_name)
        if os.path.exists(thumbnail_path) and os.path.isfile(thumbnail_path):
            os.remove(thumbnail_path)
        if os.path.exists(old_image_path) and os.path.isfile(old_image_path):
            os.remove(old_image_path)

    def _resize_images(self, png2jpeg=False):
        """Redimensionar image y thumbnail.

        El thumbnail no escalar, desajusta el diseño en las cards.

        Args:
            png2jpeg: Convertir png a jpeg?
        """
        if self.anuncio.is_premium:
            width = images_settings.GALLERY_IMAGE_PREMIUM_WIDTH
            height = images_settings.GALLERY_IMAGE_PREMIUM_HEIGHT
            quality = images_settings.GALLERY_IMAGE_QUALITY_PREMIUM
        else:
            width = images_settings.GALLERY_IMAGE_WIDTH
            height = images_settings.GALLERY_IMAGE_WIDTH
            quality = images_settings.GALLERY_IMAGE_QUALITY
        thumbnail_path = os.path.join(settings.MEDIA_ROOT, self.thumbnail)
        thumbnail_width = images_settings.GALLERY_THUMBNAIL_WIDTH
        thumbnail_height = images_settings.GALLERY_THUMBNAIL_HEIGHT
        img = ImageResize(self.image.path)
        img.png2jpeg = True
        img.quality = quality
        img.resize(self.image.path, width, height)
        img.scale = False
        img.resize(thumbnail_path, thumbnail_width, thumbnail_height)

src/apps/gallery/forms.py
from django import forms

from .models import ImageAnuncio


class ImageAnuncioForm(forms.ModelForm):
    """Form para una imagen de un anuncio."""

    class Meta:
        model = ImageAnuncio
        fields = ('image', 'anuncio', 'description')
        widgets = {
            'anuncio': forms.HiddenInput()
        }


class ImageAnuncioCreateForm(ImageAnuncioForm):
    """Cuando se crean las imágenes, no requiere ningún campo.

    Luego en la view, si un campo no tiene image, simplemente no la añade y
    no crea el objeto (usa formsets).
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['image'].required = False
        self.fields['anuncio'].required = False

src/apps/gallery/mixins/views.py
from django.shortcuts import Http404, get_object_or_404

from anuncios.models import Anuncio

from ..models import ImageAnuncio


class CheckIsOwnerByAnuncioIdMixin(object):
    """Comprueba que es el propietario por el id del anuncio."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.anuncio = None

    def dispatch(self, request, *args, **kwargs):
        """Si el anuncio no pertenece al usuario, no podrá añadir la imagen al anuncio."""
        id_anuncio = kwargs.get('id_anuncio')
        self.anuncio = get_object_or_404(Anuncio, pk=id_anuncio)
        if self.anuncio.owner != request.user:
            raise Http404
        return super().dispatch(request, *args, **kwargs)


class CheckIsOwnerByImageIdMixin(object):
    """Comprueba que es el propietario por el id de la imagen.

    Attributes:
        anuncio (Anuncio): Anuncio al que pertenece la imagen.
    """
    anuncio = None

    def dispatch(self, request, *args, **kwargs):
        """Si la imagen no pertenece al usuario, no podrá cambiar la imagen del anuncio."""
        self.anuncio = get_object_or_404(ImageAnuncio, pk=kwargs.get('pk')).anuncio
        if self.anuncio.owner.id != request.user.id:
            raise Http404
        return super().dispatch(request, *args, **kwargs)

src/apps/gallery/templates/gallery/delete_confirm.html
{% extends "base.html" %}

{% block meta_description %}Eliminar imagen, confirmación{% endblock meta_description %}
{% block head_title %}- Eliminar imagen, confirmación{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>Eliminar imagen, confirmación</h1>
      {% if image.description %}
        <p class="lead">Eliminar: {{ image.description }}</p>
      {% endif %}
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-10 m-auto">
        <div class="text-center">
          <img class="img-fluid rounded z-depth-1"
               src="{{ MEDIA_URL }}{{ image.thumbnail }}"
               alt="{{ image.description|default:'Imagen anuncio' }}"
          >
        </div>

        <div class="alert alert-warning alert-icon mt-3">¿Estas seguro que quieres eliminar la imagen?</div>

        <form method="post" action="">
          {% csrf_token %}
          <button class="btn btn-danger" type="submit">Si, eliminar</button>
          <a class="btn btn-primary" href="{% url 'gallery:anuncio_gallery_list' image.anuncio.id %}">
             Cancelar
          </a>
        </form>
      </div>
    </section>
  </section>
{% endblock content %}

src/apps/gallery/templates/gallery/gallery_list.html
{% extends "base.html" %}

{% block meta_description %}Galería de imágenes del anuncio {{ anuncio.get_title }}{% endblock meta_description %}
{% block head_title %}- Galería de imágenes del anuncio {{ anuncio.get_title }}{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>Galería de imágenes</h1>
      <hr>
      <p class="lead">{{ anuncio.get_title }}</p>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container gallery-anuncio">
    <section class="row">
      <div class="col-lg-10 m-auto">
        {% if image_list %}
          <section class="row">
            {% for image in image_list %}
              <div class="col-md-6 col-lg-4">
                {% with image.description|default:'Sin descripción' as image_description %}
                  <img class="img-anuncio img-fluid rounded z-depth-1"
                       src="{{ MEDIA_URL }}{{ image.thumbnail }}"
                       alt="{{ image_description }}"
                       title="{{ image_description }}"
                  >
                {% endwith %}
                <div class="img-actions">
                  <a class="text-success"
                     href="{% url 'gallery:image_anuncio_update' image.id %}"
                     data-toggle="tooltip"
                     title="Editar"
                  >
                    <i class="material-icons md-5">edit</i>
                  </a>
                  <a class="ml-3 text-danger"
                     href="{% url 'gallery:image_anuncio_delete' image.id %}"
                     data-toggle="tooltip"
                     title="Eliminar"
                  >
                    <i class="material-icons md-5">delete</i>
                  </a>
                </div>
              </div>
            {% endfor %}
          </section>
        {% else %}
          <h4 class="text-center">El anuncio no tiene imágenes para mostrar</h4>
        {% endif %}

        <hr>

        <div>
          <a class="btn btn-primary" href="{% url 'gallery:image_anuncio_add' anuncio.pk %}">
             Añadir imagen
          </a>
          <a class="btn btn-success" href="{% url 'anuncios:details' anuncio.pk %}">
            Ir a detalles
          </a>
        </div>
      </div>
    </section>
  </section>
{% endblock content %}

src/apps/gallery/templates/gallery/image_update.html
{% extends "base.html" %}

{% block meta_description %}Actualizar imagen {{ actual_image.description|default:'Imagen anuncio' }}{% endblock meta_description %}
{% block head_title %}- Actualizar imagen {{ actual_image.description|default:'Imagen anuncio' }}{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>Actualizar imagen</h1>
      {% if actual_image.description %}
        <p class="lead">{{ actual_image.description }}</p>
      {% endif %}
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-10 m-auto">
        <div class="text-center mb-3">
          <img id="img-anuncio"
               class="img-fluid rounded z-depth-1"
               src="{% if actual_image %}{{ MEDIA_URL }}{{ actual_image.image }}{% endif %}"
               alt="{{ actual_image.description|default:'Imagen anuncio' }}"
               width="400">
        <hr>
        </div>

        <form method="post" action="" enctype="multipart/form-data">
          {% csrf_token %}
          {% for hidden in form.hidden_fields %}
            {{ hidden }}
          {% endfor %}

          <div class="form-group">
            <label class="form-control-label" for="{{ form.image.id_for_label }}">{{ form.image.label }}</label>
            <input id="{{ form.image.id_for_label }}"
                   class="form-control-file"
                   name="image"
                   type="file"
                   value="{{ form.image.value }}"
            >
          </div>

          <div class="form-group">
            <label class="form-control-label" for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
            <input id="{{ form.description.id_for_label }}"
                   class="form-control"
                   name="description"
                   type="text"
                   value="{{ form.description.value }}"
            >
          </div>

          <hr>
          <button class="btn btn-success" type="submit">Actualizar</button>
          <a class="btn btn-primary" href="{{ HTTP_REFERER }}">Volver</a>
        </form>
      </div>
    </section>
  </section>
{% endblock content %}

{% block scripts %}
  <script>
    $(document).ready(function() {
      $('#id_image').change(function() {
        $('#img-anuncio').parent().show();
        readImagePreview('#img-anuncio', this);
      });
    });
  </script>
{% endblock scripts %}

src/apps/gallery/templates/gallery/images_add.html
{% extends "base.html" %}

{% block meta_description %}Añadir imágenes en el anuncio {{ anuncio.get_title }}{% endblock meta_description %}
{% block head_title %}- Añadir imágenes en el anuncio {{ anuncio.get_title }}{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>Añadir imágenes</h1>
      <hr>
      <p class="lead">{{ anuncio.get_title }}</p>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-8 m-auto">
        {% if restantes %}
          <div class="alert alert-info alert-icon">
            Puedes poner un máximo de <span class="badge badge-default">{{ images_max }}</span>
            imágenes, te queda por poner <span class="badge badge-default">{{ restantes }}</span>.
          </div>
        {% endif %}

        <form method="post" action="" enctype="multipart/form-data">
          {% csrf_token %}
          {{ formset.management_form }}

          {% for form in formset %}
            <div class="text-center mb-4">
              <img id="img-anuncio-{{ forloop.counter0 }}"
                   class="img-fluid rounded"
                   alt="Añadir imagen"
                   width="300"
              >
            </div>

            <div class="form-group">{{ form.image }}</div>

            <div class="form-group">
              <label class="form-control-label" for="{{ form.description.id_for_label }}">
                {{ form.description.label }}
              </label>
              <input id="{{ form.description.id_for_label }}"
                     name="form-{{ forloop.counter0 }}-description"
                     class="form-control"
                     type="text"
                     value="{% if form.description.value %}{{ form.description.value }}{% endif %}"
                     placeholder="Añade una descripción (Opcional)"
              >
            </div>
            <hr>
          {% endfor %}

          <div>
            <button class="btn btn-success" type="submit">Añadir</button>
            <a class="btn btn-primary" href="{% url 'gallery:anuncio_gallery_list' anuncio.pk %}">
              Ir a imágenes
            </a>
          </div>
        </form>
      </div>
    </section>
  </section>
{% endblock content %}

{% block scripts %}
  {% for form in formset %}
    <script>
      $(document).ready(function() {
        $('#id_form-{{ forloop.counter0 }}-image').on('change', function() {
          $('#img-anuncio-{{ forloop.counter0 }}').addClass('z-depth-1');
          readImagePreview('#img-anuncio-{{ forloop.counter0 }}', this);
        });
      });
    </script>
  {% endfor %}
{% endblock scripts %}