src/apps/alerts/urls.py
from django.conf.urls import url

from . import views

app_name = 'alerts'

urlpatterns = [

    # Detalles de una alerta.
    url(
        regex=r'^$',
        view=views.AlertUserListView.as_view(),
        name='list'
    ),

    # Detalles de una alerta.
    url(
        regex=r'^details/(?P<pk>\d+)/$',
        view=views.AlertDetailsView.as_view(),
        name='details'
    ),

    # Añadir una nueva alerta.
    url(
        regex=r'^add/(?P<category>[a-z]+)/$',
        view=views.AlertCreateView.as_view(),
        name='create'
    ),

    # Actualizar una alerta.
    url(
        regex=r'^update/(?P<pk>\d+)/$',
        view=views.AlertUpdateView.as_view(),
        name='update'
    ),

    # Elimina una alerta.
    url(
        regex=r'^delete/(?P<pk>\d+)/$',
        view=views.AlertDeleteView.as_view(),
        name='delete'
    ),

    # Elimina todas las alertas de un usuario.
    url(
        regex=r'^delete-all/$',
        view=views.AlertsAllDeleteView.as_view(),
        name='delete_all'
    ),
]

src/apps/gallery/urls.py
from django.conf.urls import url

from . import views

app_name = 'gallery'

urlpatterns = [

    # Muestra las imágenes asociadas a un anuncio.
    url(
        regex=r'^list/anuncio(?P<id_anuncio>\d+)/$',
        view=views.ImageAnuncioListView.as_view(),
        name='anuncio_gallery_list'
    ),

    # Añadir imágenes perteneciente a anuncio.
    url(
        regex=r'^add/anuncio(?P<id_anuncio>\d+)/$',
        view=views.ImageAnuncioCreateView.as_view(),
        name='image_anuncio_add'
    ),

    # Actualizar/Cambiar una imagen.
    url(
        regex=r'^update/image(?P<pk>\d+)/$',
        view=views.ImageAnuncioUpdateView.as_view(),
        name='image_anuncio_update'
    ),

    # Eliminar una imagen.
    url(
        regex=r'^delete/image(?P<pk>\d+)/$',
        view=views.ImageAnuncioDeleteView.as_view(),
        name='image_anuncio_delete'
    ),
]

src/apps/promos/urls.py
from django.conf.urls import include, url

from . import views
from .api import urls as api_urls

app_name = 'promos'

urlpatterns = [

    # Genera y envía un código de promoción a un usuario.
    url(
        regex=r'^generate/code/$',
        view=views.GenerateCodePromoView.as_view(),
        name='generate_code_promo'
    ),

    # Validación del un código.
    url(
        regex=r'^validate/$',
        view=views.PromoValidateCodeView.as_view(),
        name='validate'
    ),

    # API
    url(r'^api/', include(api_urls)),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.static import serve

from anuncios.sitemaps import AnunciosSitemap
from blog.sitemaps import BlogSitemap
from search.views import IndexSearchView
from utils.api import UserIpInfoApiView

# Sitemaps
sitemaps = {
    'anuncios': AnunciosSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    ##################################################
    # / Home page.
    url(r'^$', IndexSearchView.as_view(), name='home_page'),
    ##################################################

    # /accounts/*
    url(r'^accounts/', include('accounts.urls')),

    # /alerts/*
    url(r'^alerts/', include('alerts.urls')),

    # /anuncios/*
    url(r'^anuncios/', include('anuncios.urls')),

    # /auth/*
    url(r'^auth/', include('authentication.urls')),

    # /blog/*
    url(r'^blog/', include('blog.urls')),

    # /contact/*
    url(r'^contact/', include('contact.urls')),

    # /favorites/*
    url(r'^favorites/', include('favorites.urls')),

    # /images/*
    url(r'^gallery/', include('gallery.urls')),

    # /pages/*
    url(r'^pages/', include('pages.urls')),

    # /payments/*
    url(r'^payments/', include('payments.urls')),

    # /pmessages/*
    url(r'^pmessages/', include('pmessages.urls')),

    # /promos/*
    url(r'^promos/', include('promos.urls')),

    # /rating/*
    url(r'^ratings/', include('ratings.urls')),

    # /recommend/*
    url(r'^recommend/', include('recommend.urls')),

    # /recommend/*
    url(r'^search/', include('search.urls')),

    # /stats/*
    url(r'^stats/', include('stats.urls')),

    # /api-auth/*
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # /admin/*
    url(r'^sadmin/', admin.site.urls),
]

# Sitemaps para anuncios y blog.
urlpatterns.append(
    url(
        regex=r'^sitemap\.xml$',
        view=sitemap,
        kwargs={'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
)

# API
urlpatterns.append(

    # Obtener información de localización con la ip del usuario.
    # src/static/src/js/gmaps/geolocation.js
    # IMPORTANTE: Si se cambia el name, cambiarlo en el .js
    url(
        regex=r'^api/user-ip-info/$',
        view=UserIpInfoApiView.as_view(),
        name='api_user_ip_info'
    ),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    import debug_toolbar

    urlpatterns += [
        # /media/:<mixed>path/
        url(
            regex=r'^media/(?P<path>.*)$',
            view=serve,
            kwargs={'document_root': settings.MEDIA_ROOT}
        ),

        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

# Si se pone en DEBUG = False en desarrollo, para poder ver los static files.
# Muy importante, comentar cuando se termine.
# urlpatterns += [
#     url(
#         r'^media/(?P<path>.*)$',
#         serve,
#         {'document_root': settings.MEDIA_ROOT}
#     ),
#
#     url(
#         r'^static/(?P<path>.*)$',
#         serve,
#         {'document_root': settings.STATIC_ROOT}
#     ),
# ]

src/apps/alerts/forms.py
import sys

from django import forms

from anuncios.models import Anuncio
from utils.text import ucfirst

from . import models


class BaseAlertForm(forms.ModelForm):
    category = forms.ChoiceField(choices=Anuncio.CATEGORY_CHOICES)

    class Meta:
        localized_fields = ('precio', 'metros_cuadrados')
        help_texts = {
            'metros_cuadrados': 'Metros cuadrados mínimo',
            'habitaciones': 'Mínimo de habitaciones',
            'banos': 'Mínimo de baños',
            'precio': 'Precio máximo'
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        hidden_fields = ['owner', 'polygon', 'latitude', 'longitude']
        required_fields = ['category', 'owner', 'polygon', 'latitude', 'longitude', 'description']
        for field in self.fields:
            if field not in required_fields:
                self.fields[field].required = False
            else:
                self.fields[field].required = True
            if field in hidden_fields:
                self.fields[field].widget = forms.HiddenInput()

    def clean(self):
        """Polygon esta oculto y hay que informar si se deja en blanco.

        Al ser un campo oculto, cuando no se marca zona el error no
        se muestra. De esta manera, el usuario podrá saber que pasa.
        """
        cleaned_data = super().clean()
        polygon = cleaned_data.get('polygon')
        if not polygon:
            # Override errores del campo polygon.
            self._errors['polygon'] = ''
            raise forms.ValidationError('Has de marcar una zona en el mapa!')
        return cleaned_data

    def clean_description(self):
        """Personalizar la alerta de descripción."""
        description = self.cleaned_data['description']
        if not self.instance.pk:
            owner = self.data.get('owner')
            if models.AlertAnuncio.objects.filter(owner=owner, description=description):
                raise forms.ValidationError('Ya tienes una alerta con esa descripción')
        return description

    def clean_polygon(self):
        polygon = self.cleaned_data['polygon']
        return polygon

    @staticmethod
    def get_form_class(model_name):
        """Obtener una subclase de BaseAlertForm.

        Obtener una instancia con un nombre de CATEGORY_CHOICES.

        Returns:
            Clase en caso de existir, None en caso contrario.
        """
        module = sys.modules[__name__]
        object_model = 'Alert{}Form'.format(ucfirst(model_name))
        if hasattr(module, object_model):
            return getattr(module, object_model)


class BaseViviendaForm(BaseAlertForm):

    class Meta(BaseAlertForm.Meta):
        fields = [
            'owner',
            'description',
            'category',
            'type_anuncio',
            'estado_inmueble',
            'metros_cuadrados',
            'habitaciones',
            'banos',
            'precio',
            'latitude',
            'longitude',
            'polygon',
        ]


class AlertPisoForm(BaseViviendaForm):

    class Meta(BaseViviendaForm.Meta):
        model = models.AlertPiso


class AlertCasaForm(BaseViviendaForm):

    class Meta(BaseViviendaForm.Meta):
        model = models.AlertCasa


class AlertApartamentoForm(BaseViviendaForm):

    class Meta(BaseViviendaForm.Meta):
        model = models.AlertApartamento


class AlertHabitacionForm(BaseAlertForm):

    class Meta(BaseAlertForm.Meta):
        model = models.AlertHabitacion
        fields = [
            'owner',
            'description',
            'category',
            'type_anuncio',
            'genero',
            'internet',
            'permite_fumar_piso',
            'permite_fumar_habitacion',
            'precio',
            'latitude',
            'longitude',
            'polygon',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['type_anuncio'].widget = forms.HiddenInput()
        self.initial['type_anuncio'] = models.AlertAnuncio.ALQUILER


class AlertTerrenoForm(BaseAlertForm):

    class Meta(BaseAlertForm.Meta):
        model = models.AlertTerreno
        fields = [
            'owner',
            'description',
            'category',
            'type_anuncio',
            'metros_cuadrados',
            'precio',
            'latitude',
            'longitude',
            'polygon',
        ]


class AlertParkingForm(BaseAlertForm):

    class Meta(BaseAlertForm.Meta):
        model = models.AlertParking
        fields = [
            'owner',
            'description',
            'category',
            'type_anuncio',
            'precio',
            'latitude',
            'longitude',
            'polygon',
        ]


class AlertIndustrialForm(BaseAlertForm):

    class Meta(BaseAlertForm.Meta):
        model = models.AlertIndustrial
        fields = [
            'owner',
            'description',
            'category',
            'type_anuncio',
            'metros_cuadrados',
            'precio',
            'latitude',
            'longitude',
            'polygon',
        ]


class AlertLocalForm(BaseAlertForm):

    class Meta(BaseAlertForm.Meta):
        model = models.AlertLocal
        fields = [
            'owner',
            'description',
            'category',
            'type_anuncio',
            'metros_cuadrados',
            'precio',
            'latitude',
            'longitude',
            'polygon',
        ]

src/apps/alerts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import Http404, redirect
from django.urls import reverse
from django.views.generic import (
    CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView,
)

from anuncios.mixins.views import ClassFromCategoryNameMixin, ClassFromIDMixin

from . import forms
from .models import AlertAnuncio


class AlertUserListView(LoginRequiredMixin, ListView):
    """Lista de alertas del usuario."""
    template_name = 'alerts/list.html'
    context_object_name = 'alert_list'
    model = AlertAnuncio

    def get_queryset(self):
        return self.model.objects.filter(owner=self.request.user)


class AlertDetailsView(LoginRequiredMixin, ClassFromIDMixin, DetailView):
    template_name = 'alerts/details.html'
    context_object_name = 'alert'
    model = AlertAnuncio

    def dispatch(self, request, *args, **kwargs):
        """Las alertas solo las puede ver el owner."""
        if request.user != self.get_object().owner:
            raise Http404
        return super().dispatch(request, *args, **kwargs)


class AlertFormViewMixin(LoginRequiredMixin):
    """Mixin para crear y editar una alerta.

    Las subclases requieren de 3 atributos:
        - msg_seccess (str): Mensaje en caso de éxito.
        - title (str): Titulo, usado para el template.
        - btn_form_name (str): Texto del botón del formulario.
    """
    template_name = 'alerts/alerts_form.html'
    context_object_name = 'alert'
    model = AlertAnuncio

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = {k: v for k, v in AlertAnuncio.CATEGORY_CHOICES}
        context['btn_form_name'] = self.btn_form_name
        context['title'] = self.title
        context['category_name'] = categories.get(self.category, None)

        # Para el css, bgcolor-{{ category_css }}
        context['category_css'] = self.category.lower()
        return context

    def get_form_class(self):
        return forms.BaseAlertForm.get_form_class(self.category)

    def form_valid(self, form):
        messages.success(self.request, self.msg_seccess)
        return super().form_valid(form)


class AlertCreateView(ClassFromCategoryNameMixin, AlertFormViewMixin, CreateView):
    """Crea una nueva alerta."""
    msg_seccess = 'Se a creado una nueva alerta'
    title = 'Añadir nueva alerta '
    btn_form_name = 'Crear'

    def get_initial(self):
        initial = super().get_initial()
        initial['owner'] = self.request.user.pk
        initial['category'] = self.category
        if self.request.user.user_location.latitude:
            initial['latitude'] = self.request.user.user_location.latitude
            initial['longitude'] = self.request.user.user_location.longitude
        return initial


class AlertUpdateView(ClassFromIDMixin, AlertFormViewMixin, UpdateView):
    """Actualizar una alerta."""
    msg_seccess = 'Se a actualizado con éxito la alerta'
    btn_form_name = 'Actualizar'
    title = 'Editar alerta '

    def dispatch(self, request, *args, **kwargs):
        """Comprueba que el usuario es el owner de la alerta."""
        if request.user != self.get_object().owner:
            raise Http404
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        """Añadir al contexto la descripción de la alerta."""
        context = super().get_context_data(**kwargs)
        context['description'] = self.get_object().description
        return context


class AlertDeleteView(LoginRequiredMixin, DeleteView):
    """Un usuario elimina una alerta."""
    template_name = 'alerts/delete.html'
    context_object_name = 'alert'
    model = AlertAnuncio

    def dispatch(self, request, *args, **kwargs):
        """Comprueba que el usuario es owner de la alerta."""
        if not request.user.is_authenticated or request.user != self.get_object().owner:
            raise Http404
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        msg_success = 'Se ha eliminado la alerta'
        messages.success(self.request, msg_success)
        return reverse('alerts:list')


class AlertsAllDeleteView(LoginRequiredMixin, TemplateView):
    """Elimina todas las alertas de un usuario."""
    template_name = 'alerts/delete_all.html'

    def post(self, request, *args, **kwargs):
        if request.POST.get('delete_all'):
            AlertAnuncio.objects.filter(owner=request.user).delete()
            msg_success = 'Se han eliminado todas las alertas'
            messages.success(request, msg_success)
        return redirect(reverse('alerts:list'))

src/apps/alerts/templates/alerts/alerts_form.html
{% extends "base.html" %}
{% load djtemplateforms_tags %}

{% block meta_description %}{{ title }}{% if description %} {{ description }}{% endif %} {{ category_name|title }}{% endblock meta_description %}
{% block head_title %}- {{ title }}{% if description %} {{ description }}{% endif %} {{ category_name|title }}{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>
        {{ title }}
        <small class="badge bgcolor-{{ category_css|lower }}"> {{ category_name|title }}</small>
      </h1>
      {% if description %}<hr><p class="lead">{{ description }}</p>{% endif %}
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-12 d-lg-none text-center mb-3">
        <a class="btn-map-modal btn btn-outline-success"
           href="#modal-marker-gmap"
           data-toggle="modal"
           data-target="#map-modal"
        >
          <i class="material-icons">place</i> Añadir localización
        </a>
      </div>
    </section>

    <section class="row">
      <div class="col-lg-4 bg-light">
        <h3 class="mt-3 text-primary">Filtros</h3>
        <hr class="mt-1">
        <form method="post" action="">
          {% csrf_token %}
          <div class="form-row">
            {% form form %}

            <div class="col-12 mb-3">
              <button class="btn btn-success" type="submit">{{ btn_form_name }}</button>
              <a class="btn btn-primary" href="{% url 'alerts:list' %}">Volver</a>
            </div>
          </div>
        </form>
      </div>

      <div class="col-lg-8 d-none d-lg-block">
        <div id="map-large" style="width: 100%; height: 550px;"></div>
      </div>
    </section>
  </section>

  {% include "_gmaps_modal.html" %}
{% endblock content %}

{% block scripts %}
  {% include "_gmaps_script.html" with libraries="drawing" %}

  <script>
    // reverse campo select id_category
    var categoryInitial = $('#id_category').val().toLowerCase();
    $('#id_category').on('change', function() {
     var value = $(this).val().toLowerCase();
     if (value && value !== categoryInitial) {
       var url = '{% url "alerts:create" "piso" %}'.replace('piso', value);
       window.location.href = url;
     }
    });

    $(window).ready(function () {
      initShapeMap(true);
    });
  </script>
{% endblock scripts %}

src/apps/alerts/templates/alerts/delete.html
{% extends "base.html" %}

{% block meta_description %}Eliminar alerta {{ alert.description }}{% endblock meta_description %}
{% block head_title %}- Eliminar alerta {{ alert.description }}{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1 class="text-header">Eliminar alerta</h1>
      <hr>
      <p class="lead">{{ alert.description }}</p>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-8 m-auto">
        <div class="alert alert-warning alert-icon">
          ¿Seguro que quieres eliminar la alerta <strong class="white-text">{{ alert.description }}?</strong>
        </div>

        <form method="post" action="">
          {% csrf_token %}

          <button class="btn btn-danger" type="submit">Si, eliminar</button>
          <a class="btn btn-success" href="{% url 'alerts:list' %}">Cancelar</a>
        </form>
      </div>
    </section>
  </section>
{% endblock content %}

src/apps/alerts/templates/alerts/delete_all.html
{% extends "base.html" %}

{% block meta_description %}Eliminar todas las alertas{% endblock meta_description %}
{% block head_title %}- Eliminar todas las alertas{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>Eliminar todas las alertas</h1>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-8 m-auto">
        <div class="alert alert-warning alert-icon">¿Seguro que quieres eliminar todas tos alertas?</div>

        <form method="post" action="">
          {% csrf_token %}
          <input type="hidden" name="delete_all" value="true">

          <button class="btn btn-danger" type="submit">Si, eliminar</button>
          <a class="btn btn-success" href="{% url 'alerts:list' %}">Cancelar</a>
        </form>
      </div>
    </section>
  </section>
{% endblock content %}

src/apps/alerts/templates/alerts/details.html
{% extends "base.html" %}
{% load utils_tags %}

{% block meta_description %}Detalles de alerta {{ alert.get_category_display }} - {{ alert.description }}{% endblock meta_description %}
{% block head_title %}- Detalles de alerta {{ alert.get_category_display }} - {{ alert.description }}{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1 class="text-header">
        Detalles alerta
        <span class="badge bgcolor-{{ alert.category|lower }}">{{ alert.get_category_display }}</span>
      </h1>
      <hr>
      <p class="lead">{{ alert.description }}</p>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-12">
        <div class="text-center d-lg-none mb-3">
          <a class="btn btn-outline-success btn-map-modal"
             href="javascript:void(0);"
             data-toggle="modal"
             data-target="#map-modal"
          >
            <i class="material-icons">place</i> Mostrar en mapa
          </a>

          {# Requerido para google maps, no quitar. #}
          <input id="id_latitude" type="hidden" name="latitude" value="{{ alert.latitude }}">
          <input id="id_longitude" type="hidden" name="longitude" value="{{ alert.longitude }}">
          <input id="id_polygon" type="hidden" name="polygon" value="{{ alert.polygon }}">
        </div>
      </div>
    </section>

    <section class="row">
      <div class="col-lg-4">
        <table class="table">
          <tbody>
            {% if alert.category %}
              <tr>
                <td>Categoría</td>
                <td class="text-right">
                  <span class="badge bgcolor-{{ alert.category|lower }}">
                    {{ alert.get_category_display }}
                  </span>
                </td>
              </tr>
            {% endif %}
            {% if alert.type_anuncio %}
              <tr>
                <td>Tipo</td>
                <td class="text-right">
                  <span class="badge bgcolor-tipo-{{ alert.type_anuncio|lower }} white-text">
                    {{ alert.get_type_anuncio_display }}
                  </span>
                </td>
              </tr>
            {% endif %}
            {% if alert.estado_inmueble %}
              <tr>
                <td>Estado</td>
                <td class="text-right">
                  <span class="badge bgcolor-estado-{{ alert.estado_inmueble|lower }}">
                    {{ alert.get_estado_inmueble_display }}
                  </span>
                </td>
              </tr>
            {% endif %}
            {% if alert.metros_cuadrados %}
              <tr>
                <td>Mínimo metros cuadrados</td>
                <td class="text-right">{{ alert.metros_cuadrados }}</td>
              </tr>
            {% endif %}
            {% if alert.habitaciones %}
              <tr>
                <td>Mínimo habitaciones</td>
                <td class="text-value">{{ alert.habitaciones }}</td>
              </tr>
            {% endif %}
            {% if alert.banos %}
              <tr>
                <td>Mínimo baños</td>
                <td class="text-value">{{ alert.banos }}</td>
              </tr>
            {% endif %}
            {% if alert.genero %}
              <tr>
                <td>Genero</td>
                <td class="text-right">
                  {% if alert.genero == 'CHICO' %}
                    <span class="badge bgcolor-chico">Chicos</span>
                  {% elif alert.genero == 'CHICA' %}
                    <span class="badge bgcolor-chica">Chicas</span>
                  {% elif alert.genero == 'CHICOCHICA' %}
                    <span class="badge bgcolor-chicochica">Chicas/Chicos</span>
                  {% endif %}
                </td>
              </tr>
            {% endif %}
            {% if alert.internet %}
              <tr>
                <td>Conexión internet</td>
                <td class="text-right">{% display_for alert.internet %}</td>
              </tr>
            {% endif %}
            {% if alert.permite_fumar_piso %}
              <tr>
                <td>Permite fumar en piso</td>
                <td class="text-right">{% display_for alert.permite_fumar_piso %}</td>
              </tr>
            {% endif %}
            {% if alert.permite_fumar_habitacion %}
              <tr>
                <td>Permite fumar en habitación</td>
                <td class="text-right">{% display_for alert.permite_fumar_habitacion %}</td>
              </tr>
            {% endif %}
            {% if alert.precio %}
              <tr>
                <td>Precio máximo</td>
                <td class="text-value">{{ alert|currency }}</td>
              </tr>
            {% endif %}
            {% if alert.create_at %}
              <tr>
                <td>Fecha creación alerta</td>
                <td class="text-value">{{ alert.create_at|date:'SHORT_DATE_FORMAT' }}</td>
              </tr>
            {% endif %}
          </tbody>
        </table>

        <a class="btn btn-primary" href="{% url 'alerts:update' alert.pk %}">Editar</a>
        <a class="btn btn-success" href="{% url 'alerts:list' %}">Volver</a>
        <a class="btn btn-danger" href="{% url 'alerts:delete' alert.pk %}">Eliminar</a>
      </div>

      <div class="col-lg-8 d-none d-lg-block">
        <div id="map-large" style="width: 100%; height: 550px;"></div>
      </div>
    </section>
  </section>

  {% include "_gmaps_modal.html" %}
{% endblock content %}

{% block scripts %}
  {% include "_gmaps_script.html" with libraries="drawing" %}

  <script>
    // Cargar mapa.
    initShapeMap(false);
  </script>
{% endblock scripts %}

src/apps/alerts/templates/alerts/list.html
{% extends "accounts/base_accounts.html" %}

{% block meta_description %}Lista de alertas{% endblock meta_description %}
{% block head_title %}- Lista de alertas{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>Lista de alertas</h1>
    </section>
  </section>
{% endblock page_title %}

{% block accounts_content %}
  <section class="row">
    <div class="col-12">
      <table class="table">
        <thead>
          {% if alert_list %}
            <tr>
              <th>Identificador</th>
              <th colspan="2">Categoría</th>
            </tr>
          {% endif %}
        </thead>
        <tbody>
          {% for alert in alert_list %}
            <tr>
              <td><i class="material-icons">notifications</i> {{ alert.description }}</td>
              <td>
                <span class="badge bgcolor-{{ alert.category|lower }}">
                  {{ alert.get_category_display }}
                </span>
              </td>
              <td class="text-right">
                <a class="btn btn-outline-primary btn-sm"
                   data-toggle="tooltip"
                   title="Ver"
                   href="{% url 'alerts:details' alert.pk %}"
                >
                  <i class="material-icons md-3">remove_red_eye</i>
                </a>
                <a class="btn btn-outline-success btn-sm"
                   data-toggle="tooltip"
                   title="Editar"
                   href="{% url 'alerts:update' alert.pk %}"
                >
                  <i class="material-icons md-3">edit</i>
                </a>
                <a class="btn btn-outline-danger btn-sm"
                   data-toggle="tooltip"
                   title="Eliminar"
                   href="{% url 'alerts:delete' alert.pk %}"
                >
                  <i class="material-icons md-3">delete</i>
                </a>
              </td>
            </tr>
          {% empty %}
            <tr>
              <td class="text-center pt-4"><h5>No tienes alertas para mostrar</h5></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

      <hr>

      <a class="btn btn-primary" href="{% url 'alerts:create' 'piso' %}">
        <i class="material-icons">add_alert</i> Añadir alerta
      </a>
      {% if alert_list %}
        <a class="btn btn-outline-warning" href="{% url 'alerts:delete_all' %}">
          <i class="material-icons">delete</i> Eliminar todas
        </a>
      {% endif %}
    </div>
  </section>
{% endblock accounts_content %}